import pygame as pg
import numpy as np

def board_to_fen(board, player):
    """
    Translates our internal board representation from a 2D-numpy array into the official FEN notation.
    This function is designed to convert the current state of the board into a string format that represents 
    the placement of pieces on the board, excluding special fields (corners in this case), and indicates the current player. 

    Args:
        board (2D Array): !
        player (str): A string indicating the current player ('b' for blue or 'r' for red).

    Returns:
        str: A string representing the board state in FEN notation. The notation includes the arrangement of pieces on the board,
             excluding the pieces on special fields (corners), followed by the current player ('b' or 'r').

    Note:
        - The FEN notation generated by this function includes a custom adaptation for representing pieces: 'b0' for blue and 'r0' for red.
        - Special fields (corners of the board) are excluded from the notation.
        - The function iterates over the board in reverse order (starting from the top row) to match the FEN notation standard,
          where the board is described from the 8th row to the 1st row.
    """
    fen = ''
    special_fields = [(0, 0), (0, 7), (7, 0), (7, 7)]  # Define the corners of the board as special fields to be excluded
    for y in range(7, -1, -1):  # Iterate over rows in reverse order
        empty_count = 0  # Initialize counter for consecutive empty spaces
        row_fen = ''  # Initialize the FEN string for the current row
        for x in range(8):  # Iterate over columns
            if (x, y) in special_fields:  # Skip special fields (corners)
                continue
            piece = board[y, x]  # Get the piece at the current position
            if piece == "":  # If the space is empty
                empty_count += 1  # Increment the counter for empty spaces
            else:
                if empty_count > 0:  # If there were consecutive empty spaces before this piece
                    row_fen += str(empty_count)  # Add the count of empty spaces to the row's FEN string
                    empty_count = 0  # Reset the counter
                # Add the piece notation to the row's FEN string ('b0' for blue, 'r0' for red)
                if piece == 'b':
                    row_fen += 'b0'
                elif piece == 'r':
                    row_fen += 'r0'
                else:
                    row_fen += piece  # Add custom piece notations if any
        if empty_count > 0:  # If the row ends with consecutive empty spaces
            row_fen += str(empty_count)  # Add the count of empty spaces to the row's FEN string
        fen += row_fen  # Add the row's FEN string to the overall FEN notation
        if y != 0:  # If this is not the last row
            fen += '/'  # Add a slash to separate this row from the next
    fen += ' ' + player  # Add the current player to the end of the FEN notation
    return fen

def fen_to_board(fen):
    """
    Converts a FEN string into our internal board representation as a 2D Numpy Array.
    
    This function is designed to convert a FEN-String into the current state of the board ,excluding special fields (corners in this case).
    
    Parameters:
    - fen (str): A string representing the board state in FEN notation. The notation includes the arrangement of pieces on the board,
                 followed by the current player ('b' or 'r'). The pieces are represented by 'b' for blue and 'r' for red.
    
    Returns:
   board (2D Array): !
    
    Note:
    - The FEN string is parsed in reverse order (from the 8th row to the 1st row) to match the standard FEN notation.
    """
    board = [['' for _ in range(8)] for _ in range(8)]  # Initialize an empty 8x8 board
    rows = fen.split(' ')[0].split('/')  # Split the FEN string into rows, excluding the current player information
    
    for y, row in enumerate(rows[::-1]):  # Iterate over rows in reverse order
        x = 0  # Initialize column index
        for char in row:  # Iterate over each character in the row string
            if char.isdigit():  # If the character is a digit, it represents consecutive empty spaces
                x += int(char)  # Move the column index forward by the number of empty spaces
            else:
                # Map the FEN piece notation to our internal representation and place it on the board
                if char == 'b0':
                    board[y][x] = 'b'  # Place a blue piece
                elif char == 'r0':
                    board[y][x] = 'r'  # Place a red piece
                x += 1  # Move to the next column after placing a piece or skipping empty spaces
    
    return board